import { describe, expect, it, beforeEach, afterEach } from 'vitest'
import { mkdtemp, writeFile, mkdir, rm, readFile, copyFile, realpath } from 'node:fs/promises'
import { readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { spawn, execSync } from 'node:child_process'
import { isPidAlive, readRegistry, writeRegistry } from '../../src/flow/registry.js'
import { getTeamConfigPath, getTeamDir } from '../../src/flow/paths.js'
import type { FlowRegistryEntry } from '../../src/flow/types.js'

const repoRoot = join(import.meta.dirname, '..', '..')
const bootstrapScript = join(repoRoot, 'scripts/flow-bootstrap.js')

// Read a process command line cross-platform to assert the token never lands
// in argv. Linux exposes /proc/<pid>/cmdline (world-readable); macOS falls
// back to ps.
function readCmdline(pid: number): string {
  if (process.platform === 'linux') {
    try {
      return readFileSync(`/proc/${pid}/cmdline`, 'utf-8').replace(/\0/g, ' ')
    } catch {
      return ''
    }
  }
  try {
    return execSync(`ps -o command= -p ${pid}`, { encoding: 'utf-8' })
  } catch {
    return ''
  }
}

describe('bootstrap', () => {
  let registryDir: string
  let teamsDir: string
  let teamName: string
  let sessionId: string
  let sessionShortId: string
  let registryPath: string
  const originalRegistryDir = process.env.CC_FLOW_REGISTRY_DIR
  const originalTeamsDir = process.env.CC_FLOW_TEAMS_DIR

  beforeEach(async () => {
    registryDir = await mkdtemp(join(tmpdir(), 'cc-flow-reg-'))
    teamsDir = await mkdtemp(join(tmpdir(), 'ccx-teams-'))
    teamName = 'cc-flow-bootstrap-test'
    sessionId = 'full-session-id-1234'
    sessionShortId = sessionId.slice(0, 8)
    registryPath = `${registryDir}/${sessionShortId}.json`
    process.env.CC_FLOW_REGISTRY_DIR = registryDir
    process.env.CC_FLOW_TEAMS_DIR = teamsDir
    await mkdir(getTeamDir(teamName), { recursive: true })
    await writeFile(
      getTeamConfigPath(teamName),
      JSON.stringify({ name: teamName, leadSessionId: sessionId }),
      'utf-8',
    )
  })

  afterEach(async () => {
    if (originalRegistryDir === undefined) delete process.env.CC_FLOW_REGISTRY_DIR
    else process.env.CC_FLOW_REGISTRY_DIR = originalRegistryDir
    process.env.CC_FLOW_TEAMS_DIR = originalTeamsDir
    await rm(registryDir, { recursive: true, force: true })
    await rm(teamsDir, { recursive: true, force: true })
  })

  function runBootstrap(
    args: string[],
    extraEnv: Record<string, string> = {},
  ): Promise<{ code: number; stdout: string; stderr: string }> {
    return new Promise((resolve, reject) => {
      const child = spawn(
        process.execPath,
        [bootstrapScript, ...args],
        {
          cwd: process.cwd(),
          env: {
            ...process.env,
            CC_FLOW_REGISTRY_DIR: registryDir,
            CC_FLOW_TEAMS_DIR: teamsDir,
            ...extraEnv,
          },
          stdio: ['ignore', 'pipe', 'pipe'],
        },
      )
      let stdout = ''
      let stderr = ''
      child.stdout!.on('data', chunk => (stdout += chunk.toString()))
      child.stderr!.on('data', chunk => (stderr += chunk.toString()))
      child.on('error', reject)
      child.on('close', code => resolve({ code: code ?? 1, stdout, stderr }))
    })
  }

  it('starts a bridge, generates a token, and writes a registry entry', async () => {
    const { code, stdout, stderr } = await runBootstrap([
      '--team',
      teamName,
      '--port',
      '0',
      '--session-id',
      sessionId,
      '--registry',
      registryPath,
    ])

    expect(code).toBe(0)
    expect(stderr).toBe('')
    const match = stdout.match(/FLOW_BRIDGE_STARTED port=(\d+) pid=(\d+) registry=(\S+)/)
    expect(match).toBeTruthy()

    const [, port, pid] = match!
    expect(Number(port)).toBeGreaterThan(0)
    expect(isPidAlive(Number(pid))).toBe(true)

    const entry = await readRegistry(sessionShortId)
    expect(entry).toMatchObject({
      sessionId,
      sessionShortId,
      teamName,
    })
    // Token is generated by bootstrap (256bit hex), not passed in by the skill.
    expect(entry!.authToken).toMatch(/^[0-9a-f]{64}$/)
    expect(entry!.port).toBe(Number(port))
    expect(entry!.pid).toBe(Number(pid))
    // The generated token must never leak into stdout.
    expect(stdout).not.toContain(entry!.authToken)

    // Clean up the spawned bridge.
    const off = await runBootstrap(['--off', '--registry', registryPath])
    expect(off.code).toBe(0)
    expect(isPidAlive(Number(pid))).toBe(false)
  })

  it('honors CC_FLOW_TOKEN env override instead of generating', async () => {
    const token = 'explicit-override-token-0123456789abcdef'
    const { code } = await runBootstrap(
      ['--team', teamName, '--port', '0', '--session-id', sessionId, '--registry', registryPath],
      { CC_FLOW_TOKEN: token },
    )
    expect(code).toBe(0)
    const entry = await readRegistry(sessionShortId)
    expect(entry!.authToken).toBe(token)

    await runBootstrap(['--off', '--registry', registryPath])
  })

  it('never passes the token through the bridge process command line', async () => {
    const token = 'cmdline-secret-token-0123456789abcdef0123'
    const { code } = await runBootstrap(
      ['--team', teamName, '--port', '0', '--session-id', sessionId, '--registry', registryPath],
      { CC_FLOW_TOKEN: token },
    )
    expect(code).toBe(0)
    const entry = await readRegistry(sessionShortId)
    // The bridge child's argv must not contain the token.
    expect(readCmdline(entry!.pid)).not.toContain(token)

    await runBootstrap(['--off', '--registry', registryPath])
    expect(isPidAlive(entry!.pid)).toBe(false)
  })

  it('rejects a weak CC_FLOW_TOKEN override', async () => {
    const { code, stderr } = await runBootstrap(
      ['--team', teamName, '--port', '0', '--session-id', sessionId, '--registry', registryPath],
      { CC_FLOW_TOKEN: 'too-short' },
    )
    expect(code).not.toBe(0)
    expect(stderr).toContain('too weak')
  })

  it('writes description and project info to the registry', async () => {
    const projectDirRaw = await mkdtemp(join(tmpdir(), 'cc-flow-project-'))
    await writeFile(join(projectDirRaw, 'package.json'), JSON.stringify({ name: 'test-project' }), 'utf-8')
    const projectDir = await realpath(projectDirRaw)

    const originalCwd = process.cwd()
    process.chdir(projectDir)
    try {
      const { code, stdout, stderr } = await runBootstrap([
        '--team',
        teamName,
        '--port',
        '0',
        '--session-id',
        sessionId,
        '--registry',
        registryPath,
        '--description',
        'fixing the registry metadata schema for plugin migration',
      ])
      if (code !== 0) {
        console.error('bootstrap stderr:', stderr)
      }
      expect(code).toBe(0)
      const match = stdout.match(/FLOW_BRIDGE_STARTED port=(\d+) pid=(\d+) registry=(\S+)/)!
      const pid = Number(match[2])

      const entry = await readRegistry(sessionShortId)
      expect(entry!.description).toBe('fixing the registry metadata schema for plugin migration')
      expect(entry!.project).toEqual({
        name: 'test-project',
        path: projectDir,
        rootPath: projectDir,
      })

      await runBootstrap(['--off', '--registry', registryPath])
      expect(isPidAlive(pid)).toBe(false)
    } finally {
      process.chdir(originalCwd)
      await rm(projectDirRaw, { recursive: true, force: true })
    }
  })

  it('truncates long descriptions to 100 characters', async () => {
    const longDescription = 'a'.repeat(150)
    const { code } = await runBootstrap([
      '--team',
      teamName,
      '--port',
      '0',
      '--session-id',
      sessionId,
      '--registry',
      registryPath,
      '--description',
      longDescription,
    ])
    expect(code).toBe(0)

    const entry = await readRegistry(sessionShortId)
    expect(entry!.description.length).toBe(100)
    expect(entry!.description).toBe('a'.repeat(100))

    const pid = entry!.pid
    await runBootstrap(['--off', '--registry', registryPath])
    expect(isPidAlive(pid)).toBe(false)
  })

  it('honors --registry even when it diverges from the default registry dir', async () => {
    // CC_FLOW_REGISTRY_DIR points at registryDir, but --registry points elsewhere.
    // The entry must land at the --registry path, never the default dir.
    const elsewhere = await mkdtemp(join(tmpdir(), 'cc-flow-elsewhere-'))
    const elsewhereRegistry = `${elsewhere}/${sessionShortId}.json`
    try {
      const { code } = await runBootstrap([
        '--team',
        teamName,
        '--port',
        '0',
        '--session-id',
        sessionId,
        '--registry',
        elsewhereRegistry,
      ])
      expect(code).toBe(0)

      const entry = JSON.parse(await readFile(elsewhereRegistry, 'utf-8'))
      expect(entry.sessionShortId).toBe(sessionShortId)
      // Nothing leaked into the default registry dir.
      await expect(readFile(`${registryDir}/${sessionShortId}.json`, 'utf-8')).rejects.toThrow(
        'ENOENT',
      )

      const off = await runBootstrap(['--off', '--registry', elsewhereRegistry])
      expect(off.code).toBe(0)
      await expect(readFile(elsewhereRegistry, 'utf-8')).rejects.toThrow('ENOENT')
    } finally {
      await rm(elsewhere, { recursive: true, force: true })
    }
  })

  it('reuses an existing bridge for the same session', async () => {
    const first = await runBootstrap([
      '--team',
      teamName,
      '--port',
      '0',
      '--session-id',
      sessionId,
      '--registry',
      registryPath,
    ])
    expect(first.code).toBe(0)
    const started = first.stdout.match(/FLOW_BRIDGE_STARTED port=(\d+) pid=(\d+)/)!
    const pid = Number(started[2])

    const second = await runBootstrap([
      '--team',
      teamName,
      '--port',
      '0',
      '--session-id',
      sessionId,
      '--registry',
      registryPath,
    ])
    expect(second.code).toBe(0)
    expect(second.stdout).toContain('FLOW_BRIDGE_ALREADY_RUNNING')
    expect(second.stdout).toContain(pid.toString())
    expect(second.stdout).not.toContain('FLOW_BRIDGE_STARTED')
    // Token must not appear in the already-running output either.
    const entry = await readRegistry(sessionShortId)
    expect(second.stdout).not.toContain(entry!.authToken)

    await runBootstrap(['--off', '--registry', registryPath])
    expect(isPidAlive(pid)).toBe(false)
  })

  it('--off skips untrusted registry entries', async () => {
    const evilTeam = 'not-cc-flow-team'
    const evilRegistry = `${registryDir}/evil-se.json`
    const entry: FlowRegistryEntry = {
      sessionId: 'evil-session-id-0000',
      sessionShortId: 'evil-se',
      teamName: evilTeam,
      port: 12345,
      pid: 99999,
      authToken: 'evil-token',
      startedAt: new Date().toISOString(),
      description: 'evil',
      project: { name: 'evil', path: '/evil', rootPath: '/evil' },
    }
    await writeRegistry(entry)

    const off = await runBootstrap(['--off', '--registry', evilRegistry])
    expect(off.code).toBe(0)
    expect(off.stderr).toContain('skipping untrusted registry entry')
    expect(off.stdout).toContain('FLOW_OFF: cleaned 0 session(s)')

    // Registry should NOT have been deleted because the entry was skipped.
    const stillThere = await readFile(evilRegistry, 'utf-8')
    expect(stillThere).toContain(evilTeam)
  })

  it('rejects a session-id shorter than 8 characters', async () => {
    const { code, stderr } = await runBootstrap([
      '--team',
      teamName,
      '--port',
      '0',
      '--session-id',
      'short',
      '--registry',
      registryPath,
    ])
    expect(code).not.toBe(0)
    expect(stderr).toContain('at least 8 characters')
  })

  it('rejects a flag used as another flag value', async () => {
    const { code, stderr } = await runBootstrap([
      '--team',
      teamName,
      '--port',
      '0',
      '--registry',
      '--session-id',
      sessionId,
    ])
    expect(code).not.toBe(0)
    expect(stderr).toContain('--registry is required')
  })

  it('reports a clear error when the bridge bundle cannot be spawned', async () => {
    const tmpBinDir = await mkdtemp(join(tmpdir(), 'cc-flow-bootstrap-bin-'))
    await copyFile(bootstrapScript, join(tmpBinDir, 'flow-bootstrap.js'))

    const { code, stderr } = await new Promise<{ code: number; stdout: string; stderr: string }>(
      (resolve, reject) => {
        const child = spawn(
          process.execPath,
          [
            join(tmpBinDir, 'flow-bootstrap.js'),
            '--team',
            teamName,
            '--port',
            '0',
            '--session-id',
            sessionId,
            '--registry',
            registryPath,
          ],
          {
            cwd: process.cwd(),
            env: {
              ...process.env,
              CC_FLOW_REGISTRY_DIR: registryDir,
              CC_FLOW_TEAMS_DIR: teamsDir,
            },
            stdio: ['ignore', 'pipe', 'pipe'],
          },
        )
        let stdout = ''
        let stderr = ''
        child.stdout!.on('data', chunk => (stdout += chunk.toString()))
        child.stderr!.on('data', chunk => (stderr += chunk.toString()))
        child.on('error', reject)
        child.on('close', code => resolve({ code: code ?? 1, stdout, stderr }))
      },
    )

    await rm(tmpBinDir, { recursive: true, force: true })

    expect(code).not.toBe(0)
    expect(stderr).toMatch(/Failed to spawn|Bridge process exited/)
  }, 10000)
})
